openapi: 3.0.0
info:
  contact:
    email: support@yugabyte.com
    name: Yugabyte Cloud Support
    url: https://support.yugabyte.com/
  description: YugabyteDB as a Service
  license:
    name: Properietary (TBD)
    url: https://www.yugabyte.com/yugabyte-cloud-terms-of-service
  termsOfService: https://www.yugabyte.com/yugabyte-cloud-terms-of-service
  title: Yugabyte Cloud
  version: v1
servers:
- description: Endpoint of the API server
  url: '{protocol}://{host_port}/api'
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    host_port:
      default: localhost:1323
security:
- BearerAuthToken: []
tags:
- description: APIs for cluster CRUD
  name: cluster
- description: APIs for getting information about an existing cluster
  name: cluster-info
paths:
  /cluster:
    delete:
      description: Submit task to delete a Yugabyte Cluster
      operationId: deleteCluster
      responses:
        "200":
          description: Successfully submitted delete cluster request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Submit task to delete a cluster
      tags:
      - cluster
    get:
      description: Get a Yugabyte Cluster
      operationId: getCluster
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster_Response'
          description: Cluster response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get a cluster
      tags:
      - cluster
    put:
      description: Submit task to edit a Yugabyte Cluster
      operationId: editCluster
      requestBody:
        $ref: '#/components/requestBodies/ClusterSpec'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster_Response'
          description: Cluster response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Submit task to edit a cluster
      tags:
      - cluster
  /live_queries:
    get:
      description: Get the Live Queries in a Yugabyte Cluster
      operationId: getLiveQueries
      parameters:
      - description: type of queries for which to retrieve Live Queries (YSQL or YCQL)
        explode: false
        in: query
        name: api
        required: false
        schema:
          enum:
          - YSQL
          - YCQL
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiveQueryResponseSchema'
          description: Live Queries of a Cluster
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get the live queries in a cluster
      tags:
      - cluster-info
  /slow_queries:
    get:
      description: Get the Slow Queries in a Yugabyte Cluster
      operationId: getSlowQueries
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlowQueryResponseSchema'
          description: Slow Queries of a Cluster
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get the slow queries in a cluster
      tags:
      - cluster-info
  /nodes:
    get:
      description: Get nodes for a Yugabyte cluster
      operationId: getClusterNodes
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster_Nodes_Response'
          description: Cluster nodes response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get the nodes for a cluster
      tags:
      - cluster-info
  /metrics:
    get:
      description: Get metrics for a Yugabyte cluster
      operationId: getClusterMetric
      parameters:
      - description: Which metrics to retrieve results for
        explode: false
        in: query
        name: metrics
        required: true
        schema:
          type: string
        style: form
      - description: Node name within the cluster
        explode: false
        in: query
        name: node_name
        required: false
        schema:
          type: string
        style: form
      - description: Region name to filter for the given cluster
        explode: false
        in: query
        name: region
        required: false
        schema:
          type: string
        style: form
      - description: Start of range of time series data (in epoch seconds)
        explode: false
        in: query
        name: start_time
        required: false
        schema:
          format: int64
          minimum: 0
          type: integer
        style: form
      - description: End of range of time series data (in epoch seconds)
        explode: false
        in: query
        name: end_time
        required: false
        schema:
          format: int64
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metric_Response'
          description: Metric response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get a metric for a cluster
      tags:
      - cluster-info
  /tables:
    get:
      description: Get list of tables per YB API (YCQL/YSQL)
      operationId: getClusterTables
      parameters:
      - description: Which DB API to get tables for (YCQL/YSQL)
        explode: false
        in: query
        name: api
        required: false
        schema:
          enum:
          - YCQL
          - YSQL
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster_table_list_response'
          description: List of cluster tables
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get list of DB tables per YB API (YCQL/YSQL)
      tags:
      - cluster-info
  /health-check:
    get:
      description: Get health information about the cluster
      operationId: getClusterHealthCheck
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health_Check_Response'
          description: Successful health check response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get health information about the cluster
      tags:
      - cluster-info
  /tablets:
    get:
      description: Get list of tablets
      operationId: getClusterTablets
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster_tablet_list_response'
          description: List of cluster tablets
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get list of tablets
      tags:
      - cluster-info
  /version:
    get:
      description: Get YugabyteDB version
      operationId: getVersion
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
          description: Version info for YugabyteDB
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Get YugabyteDB version
      tags:
      - cluster-info
  /is_load_balancer_idle:
    get:
      description: Check if cluster load balancer is idle
      operationId: getIsLoadBalancerIdle
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Is_load_balancer_idle'
          description: Is load balancer idle
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: API Error
      summary: Check if cluster load balancer is idle
      tags:
      - cluster-info
components:
  requestBodies:
    ClusterSpec:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ClusterSpec'
      description: DB Cluster to be updated
  responses:
    ClusterResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cluster_Response'
      description: Cluster response
    ApiError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
      description: API Error
    LiveQueryResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LiveQueryResponseSchema'
      description: Live Queries of a Cluster
    SlowQueryResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SlowQueryResponseSchema'
      description: Slow Queries of a Cluster
    ClusterNodeListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cluster_Nodes_Response'
      description: Cluster nodes response
    MetricResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Metric_Response'
      description: Metric response
    ClusterTableListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cluster_table_list_response'
      description: List of cluster tables
    HealthCheckResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Health_Check_Response'
      description: Successful health check response
    ClusterTabletListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cluster_tablet_list_response'
      description: List of cluster tablets
    VersionInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VersionInfo'
      description: Version info for YugabyteDB
  schemas:
    CloudEnum:
      default: MANUAL
      description: Which cloud the cluster is deployed in
      enum:
      - AWS
      - GCP
      - MANUAL
      title: Cloud Enum
      type: string
    CloudInfo:
      description: Cloud deployment information
      example:
        region: us-west2
      properties:
        code:
          $ref: '#/components/schemas/CloudEnum'
        region:
          default: us-west2
          minLength: 1
          type: string
      required:
      - code
      - region
      title: Cloud Info
      type: object
    ClusterFaultTolerance:
      default: ZONE
      description: The level of fault tolerance for the cluster
      enum:
      - NONE
      - NODE
      - ZONE
      - REGION
      title: Cluster Fault Tolerance
      type: string
    ClusterNodeInfo:
      description: Node level information
      example:
        disk_size_used_gb: 5.962133916683182
        num_cores: 2
        memory_mb: 6.027456183070403
        cpu_usage: 5.637376656633329
        disk_size_gb: 1.4658129805029452
      properties:
        memory_mb:
          default: 0
          description: The total amount of RAM (MB) used by all nodes
          format: double
          type: number
        disk_size_gb:
          default: 0
          description: The total size of disk (GB)
          format: double
          type: number
        disk_size_used_gb:
          default: 0
          description: The total size of used disk space (GB)
          format: double
          type: number
        cpu_usage:
          default: 0
          description: The average CPU usage over all nodes
          format: double
          type: number
        num_cores:
          default: 0
          description: The number of CPU cores per node
          type: integer
      required:
      - disk_size_gb
      - memory_mb
      - num_cores
      title: Cluster Node Info
      type: object
    ClusterInfo:
      description: Cluster level information
      example:
        node_info:
          disk_size_used_gb: 5.962133916683182
          num_cores: 2
          memory_mb: 6.027456183070403
          cpu_usage: 5.637376656633329
          disk_size_gb: 1.4658129805029452
        is_production: false
        version: 7
        num_nodes: 2
      properties:
        num_nodes:
          default: 3
          description: How many nodes are in the cluster
          maximum: 24
          minimum: 1
          type: integer
        fault_tolerance:
          $ref: '#/components/schemas/ClusterFaultTolerance'
        node_info:
          $ref: '#/components/schemas/ClusterNodeInfo'
        is_production:
          default: false
          description: Describes if the cluster is a production cluster
          type: boolean
        version:
          description: cluster data version
          nullable: true
          type: integer
      required:
      - cluster_tier
      - fault_tolerance
      - is_production
      - node_info
      - num_nodes
      title: Cluster Info
      type: object
    PlacementInfo:
      example:
        cloud_info:
          region: us-west2
        num_nodes: 22
      properties:
        cloud_info:
          $ref: '#/components/schemas/CloudInfo'
        num_nodes:
          default: 3
          description: How many nodes are in the region
          maximum: 24
          minimum: 1
          type: integer
      required:
      - cloud_info
      - num_nodes
      type: object
    ClusterRegionInfo:
      description: Cluster region info list
      example:
        placement_info:
          cloud_info:
            region: us-west2
          num_nodes: 22
      properties:
        placement_info:
          $ref: '#/components/schemas/PlacementInfo'
      required:
      - placement_info
      title: Cluster Region Info
      type: object
    EncryptionInfo:
      description: Cluster encryption info
      example:
        encryption_in_transit: false
        encryption_at_rest: false
      properties:
        encryption_at_rest:
          default: false
          type: boolean
        encryption_in_transit:
          default: false
          type: boolean
      title: Encryption Info
      type: object
    ClusterSpec:
      description: Cluster spec
      example:
        cluster_region_info:
        - placement_info:
            cloud_info:
              region: us-west2
            num_nodes: 22
        - placement_info:
            cloud_info:
              region: us-west2
            num_nodes: 22
        name: name
        cloud_info:
          region: us-west2
        encryption_info:
          encryption_in_transit: false
          encryption_at_rest: false
        cluster_info:
          node_info:
            disk_size_used_gb: 5.962133916683182
            num_cores: 2
            memory_mb: 6.027456183070403
            cpu_usage: 5.637376656633329
            disk_size_gb: 1.4658129805029452
          is_production: false
          version: 7
          num_nodes: 2
      properties:
        name:
          description: The name of the cluster
          maxLength: 63
          minLength: 3
          pattern: ^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$
          type: string
        cloud_info:
          $ref: '#/components/schemas/CloudInfo'
        cluster_info:
          $ref: '#/components/schemas/ClusterInfo'
        cluster_region_info:
          items:
            $ref: '#/components/schemas/ClusterRegionInfo'
          nullable: true
          type: array
          uniqueItems: true
        encryption_info:
          $ref: '#/components/schemas/EncryptionInfo'
      required:
      - cloud_info
      - cluster_info
      - encryption_info
      - name
      - network_info
      - software_info
      title: Cluster Specification
      type: object
    EntityMetadata:
      description: Common metadata for entities
      example:
        updated_on: updated_on
        created_on: created_on
      properties:
        created_on:
          description: Timestamp when the entity was created (UTC)
          nullable: true
          type: string
        updated_on:
          description: Timestamp when the entity was last updated (UTC)
          nullable: true
          type: string
      title: Entity Metadata
      type: object
    ClusterDataInfo:
      example:
        metadata:
          updated_on: updated_on
          created_on: created_on
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        state: state
        software_version: software_version
      properties:
        id:
          description: The UUID of the cluster
          format: uuid
          type: string
        state:
          description: The current state of the cluster
          type: string
        software_version:
          description: The current version of YugabyteDB installed on the cluster
          type: string
        metadata:
          $ref: '#/components/schemas/EntityMetadata'
      required:
      - id
      - metadata
      - project_id
      - state
      type: object
    ClusterData:
      description: Cluster data
      example:
        spec:
          cluster_region_info:
          - placement_info:
              cloud_info:
                region: us-west2
              num_nodes: 22
          - placement_info:
              cloud_info:
                region: us-west2
              num_nodes: 22
          name: name
          cloud_info:
            region: us-west2
          encryption_info:
            encryption_in_transit: false
            encryption_at_rest: false
          cluster_info:
            node_info:
              disk_size_used_gb: 5.962133916683182
              num_cores: 2
              memory_mb: 6.027456183070403
              cpu_usage: 5.637376656633329
              disk_size_gb: 1.4658129805029452
            is_production: false
            version: 7
            num_nodes: 2
        info:
          metadata:
            updated_on: updated_on
            created_on: created_on
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          state: state
          software_version: software_version
      properties:
        spec:
          $ref: '#/components/schemas/ClusterSpec'
        info:
          $ref: '#/components/schemas/ClusterDataInfo'
      required:
      - info
      - spec
      title: Cluster Data
      type: object
    ApiError:
      properties:
        error:
          $ref: '#/components/schemas/ApiError_error'
      title: API Error
      type: object
    LiveQueryResponseYSQLQueryItem:
      description: Schema for Live Query Response YSQL Query Item
      example:
        app_name: app_name
        client_port: client_port
        db_name: db_name
        query_start_time: query_start_time
        query: query
        node_name: node_name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        elapsed_millis: 6
        session_status: session_status
        client_host: client_host
      properties:
        id:
          format: uuid
          type: string
        node_name:
          type: string
        db_name:
          type: string
        session_status:
          type: string
        query:
          type: string
        elapsed_millis:
          format: int64
          type: integer
        query_start_time:
          type: string
        app_name:
          type: string
        client_host:
          type: string
        client_port:
          type: string
      title: Live Query Response YSQL Query Item
      type: object
    LiveQueryResponseYSQLData:
      description: Schema for Live Query Response YSQL Data
      example:
        error_count: 0
        queries:
        - app_name: app_name
          client_port: client_port
          db_name: db_name
          query_start_time: query_start_time
          query: query
          node_name: node_name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          elapsed_millis: 6
          session_status: session_status
          client_host: client_host
        - app_name: app_name
          client_port: client_port
          db_name: db_name
          query_start_time: query_start_time
          query: query
          node_name: node_name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          elapsed_millis: 6
          session_status: session_status
          client_host: client_host
      properties:
        error_count:
          description: Count of Errors
          type: integer
        queries:
          items:
            $ref: '#/components/schemas/LiveQueryResponseYSQLQueryItem'
          type: array
      title: Live Query Response YSQL Data
      type: object
    LiveQueryResponseYCQLQueryItem:
      description: Schema for Live Query Response YCQL Query Item
      example:
        keyspace: keyspace
        client_port: client_port
        query: query
        node_name: node_name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        elapsed_millis: 5
        type: type
        client_host: client_host
      properties:
        id:
          format: uuid
          type: string
        node_name:
          type: string
        keyspace:
          type: string
        query:
          type: string
        type:
          type: string
        elapsed_millis:
          format: int64
          type: integer
        client_host:
          type: string
        client_port:
          type: string
      title: Live Query Response YCQL Query Item
      type: object
    LiveQueryResponseYCQLData:
      description: Schema for Live Query Response YCQL Data
      example:
        error_count: 1
        queries:
        - keyspace: keyspace
          client_port: client_port
          query: query
          node_name: node_name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          elapsed_millis: 5
          type: type
          client_host: client_host
        - keyspace: keyspace
          client_port: client_port
          query: query
          node_name: node_name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          elapsed_millis: 5
          type: type
          client_host: client_host
      properties:
        error_count:
          description: Count of Errors
          type: integer
        queries:
          items:
            $ref: '#/components/schemas/LiveQueryResponseYCQLQueryItem'
          type: array
      title: Live Query Response YCQL Data
      type: object
    LiveQueryResponseData:
      description: Live Query Response Data
      example:
        ysql:
          error_count: 0
          queries:
          - app_name: app_name
            client_port: client_port
            db_name: db_name
            query_start_time: query_start_time
            query: query
            node_name: node_name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            elapsed_millis: 6
            session_status: session_status
            client_host: client_host
          - app_name: app_name
            client_port: client_port
            db_name: db_name
            query_start_time: query_start_time
            query: query
            node_name: node_name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            elapsed_millis: 6
            session_status: session_status
            client_host: client_host
        ycql:
          error_count: 1
          queries:
          - keyspace: keyspace
            client_port: client_port
            query: query
            node_name: node_name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            elapsed_millis: 5
            type: type
            client_host: client_host
          - keyspace: keyspace
            client_port: client_port
            query: query
            node_name: node_name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            elapsed_millis: 5
            type: type
            client_host: client_host
      properties:
        ysql:
          $ref: '#/components/schemas/LiveQueryResponseYSQLData'
        ycql:
          $ref: '#/components/schemas/LiveQueryResponseYCQLData'
      title: Live Query Response Data
      type: object
    LiveQueryResponseSchema:
      description: Live Query Response Schema
      example:
        data:
          ysql:
            error_count: 0
            queries:
            - app_name: app_name
              client_port: client_port
              db_name: db_name
              query_start_time: query_start_time
              query: query
              node_name: node_name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              elapsed_millis: 6
              session_status: session_status
              client_host: client_host
            - app_name: app_name
              client_port: client_port
              db_name: db_name
              query_start_time: query_start_time
              query: query
              node_name: node_name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              elapsed_millis: 6
              session_status: session_status
              client_host: client_host
          ycql:
            error_count: 1
            queries:
            - keyspace: keyspace
              client_port: client_port
              query: query
              node_name: node_name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              elapsed_millis: 5
              type: type
              client_host: client_host
            - keyspace: keyspace
              client_port: client_port
              query: query
              node_name: node_name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              elapsed_millis: 5
              type: type
              client_host: client_host
      properties:
        data:
          $ref: '#/components/schemas/LiveQueryResponseData'
      title: Live Query Response Schema
      type: object
    SlowQueryResponseYSQLQueryItem:
      description: Schema for Slow Query Response YSQL Query Item
      example:
        query: query
        datname: datname
        local_blks_written: 5
        rows: 3
        stddev_time: 2.027123023002322
        min_time: 9.301444243932576
        queryid: 6
        rolname: rolname
        local_blks_hit: 5
        calls: 1
        max_time: 2.3021358869347655
        mean_time: 7.061401241503109
        total_time: 4.145608029883936
      properties:
        queryid:
          format: int64
          type: integer
        query:
          type: string
        rolname:
          type: string
        datname:
          type: string
        calls:
          type: integer
        local_blks_hit:
          type: integer
        local_blks_written:
          type: integer
        max_time:
          format: double
          type: number
        mean_time:
          format: double
          type: number
        min_time:
          format: double
          type: number
        rows:
          type: integer
        stddev_time:
          format: double
          type: number
        total_time:
          format: double
          type: number
      title: Slow Query Response YSQL Query Item
      type: object
    SlowQueryResponseYSQLData:
      description: Schema for Slow Query Response YSQL Data
      example:
        error_count: 0
        queries:
        - query: query
          datname: datname
          local_blks_written: 5
          rows: 3
          stddev_time: 2.027123023002322
          min_time: 9.301444243932576
          queryid: 6
          rolname: rolname
          local_blks_hit: 5
          calls: 1
          max_time: 2.3021358869347655
          mean_time: 7.061401241503109
          total_time: 4.145608029883936
        - query: query
          datname: datname
          local_blks_written: 5
          rows: 3
          stddev_time: 2.027123023002322
          min_time: 9.301444243932576
          queryid: 6
          rolname: rolname
          local_blks_hit: 5
          calls: 1
          max_time: 2.3021358869347655
          mean_time: 7.061401241503109
          total_time: 4.145608029883936
      properties:
        error_count:
          description: Count of Errors
          type: integer
        queries:
          items:
            $ref: '#/components/schemas/SlowQueryResponseYSQLQueryItem'
          type: array
      title: Slow Query Response YSQL Data
      type: object
    SlowQueryResponseData:
      description: Slow Query Response Data
      example:
        ysql:
          error_count: 0
          queries:
          - query: query
            datname: datname
            local_blks_written: 5
            rows: 3
            stddev_time: 2.027123023002322
            min_time: 9.301444243932576
            queryid: 6
            rolname: rolname
            local_blks_hit: 5
            calls: 1
            max_time: 2.3021358869347655
            mean_time: 7.061401241503109
            total_time: 4.145608029883936
          - query: query
            datname: datname
            local_blks_written: 5
            rows: 3
            stddev_time: 2.027123023002322
            min_time: 9.301444243932576
            queryid: 6
            rolname: rolname
            local_blks_hit: 5
            calls: 1
            max_time: 2.3021358869347655
            mean_time: 7.061401241503109
            total_time: 4.145608029883936
      properties:
        ysql:
          $ref: '#/components/schemas/SlowQueryResponseYSQLData'
      title: Slow Query Response Data
      type: object
    SlowQueryResponseSchema:
      description: Slow Query Response Schema
      example:
        data:
          ysql:
            error_count: 0
            queries:
            - query: query
              datname: datname
              local_blks_written: 5
              rows: 3
              stddev_time: 2.027123023002322
              min_time: 9.301444243932576
              queryid: 6
              rolname: rolname
              local_blks_hit: 5
              calls: 1
              max_time: 2.3021358869347655
              mean_time: 7.061401241503109
              total_time: 4.145608029883936
            - query: query
              datname: datname
              local_blks_written: 5
              rows: 3
              stddev_time: 2.027123023002322
              min_time: 9.301444243932576
              queryid: 6
              rolname: rolname
              local_blks_hit: 5
              calls: 1
              max_time: 2.3021358869347655
              mean_time: 7.061401241503109
              total_time: 4.145608029883936
      properties:
        data:
          $ref: '#/components/schemas/SlowQueryResponseData'
      title: Slow Query Response Schema
      type: object
    NodeData:
      description: Node data
      example:
        is_master_up: true
        is_master: true
        is_tserver: true
        is_node_up: true
        name: name
        host: host
        is_bootstrapping: true
        cloud_info:
          cloud: cloud
          zone: zone
          region: region
        metrics:
          system_tablets_total: 0
          system_tablets_leaders: 0
          write_ops_per_sec: 5.637376656633329
          ram_provisioned_bytes: 0
          time_since_hb_sec: 2.3021358869347655
          active_connections:
            ysql: 0
            ycql: 0
          total_sst_file_size_bytes: 6
          uncompressed_sst_file_size_bytes: 1
          read_ops_per_sec: 5.962133916683182
          user_tablets_leaders: 0
          ram_used_bytes: 0
          memory_used_bytes: 0
          uptime_seconds: 0
          user_tablets_total: 0
          disk_provisioned_bytes: 0
          master_uptime_us: 0
        software_version: software_version
      properties:
        name:
          nullable: false
          type: string
        host:
          nullable: false
          type: string
        is_node_up:
          type: boolean
        is_master:
          type: boolean
        is_tserver:
          type: boolean
        is_master_up:
          type: boolean
        is_bootstrapping:
          type: boolean
        metrics:
          $ref: '#/components/schemas/NodeData_metrics'
        cloud_info:
          $ref: '#/components/schemas/NodeData_cloud_info'
        software_version:
          type: string
      required:
      - cloud_info
      - host
      - is_bootstrapping
      - is_master
      - is_master_up
      - is_node_up
      - is_tserver
      - metrics
      - name
      - software_version
      type: object
    MetricData:
      description: Metric data
      example:
        values:
        - - 0.8008281904610115
          - 0.8008281904610115
        - - 0.8008281904610115
          - 0.8008281904610115
        name: name
      properties:
        name:
          description: The name of the metric
          type: string
        values:
          description: Array of (timestamp, value) tuples
          items:
            items:
              format: double
              type: number
            maxItems: 2
            minItems: 2
            type: array
          type: array
      required:
      - name
      - values
      title: Metric Data
      type: object
    YbApiEnum:
      description: Type of DB API (YSQL/YCQL)
      enum:
      - YSQL
      - YCQL
      title: Yb Api Enum
      type: string
    ClusterTable:
      description: Model representing a DB table
      example:
        keyspace: keyspace
        size_bytes: 0
        name: name
      properties:
        name:
          minLength: 1
          nullable: false
          type: string
        keyspace:
          minLength: 1
          nullable: false
          type: string
        type:
          $ref: '#/components/schemas/YbApiEnum'
        size_bytes:
          format: int64
          minimum: 0
          type: integer
      required:
      - keyspace
      - name
      - size_bytes
      - type
      title: Cluster Table Object
      type: object
    ClusterTableData:
      description: List of cluster tables
      items:
        $ref: '#/components/schemas/ClusterTable'
      nullable: false
      title: Cluster Table Data
      type: array
      uniqueItems: true
    HealthCheckInfo:
      example:
        most_recent_uptime: 0
        dead_nodes:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        leaderless_tablets:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        under_replicated_tablets:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        dead_nodes:
          description: UUIDs of dead nodes
          items:
            format: uuid
            type: string
          type: array
        most_recent_uptime:
          format: int64
          minimum: 0
          type: integer
        under_replicated_tablets:
          description: UUIDs of under-replicated tablets
          items:
            format: uuid
            type: string
          type: array
        leaderless_tablets:
          description: UUIDs of leaderless tablets
          items:
            format: uuid
            type: string
          type: array
      required:
      - dead_nodes
      - leaderless_tablets
      - most_recent_uptime
      - under_replicated_tablets
      title: Health Check Info
      type: object
    ClusterTablet:
      description: Model representing a tablet
      example:
        tablet_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        namespace: namespace
        table_uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        table_name: table_name
        has_leader: true
      properties:
        namespace:
          type: string
        table_name:
          type: string
        table_uuid:
          format: uuid
          type: string
        tablet_id:
          format: uuid
          type: string
        has_leader:
          type: boolean
      required:
      - has_leader
      - namespace
      - table_id
      - table_name
      - table_uuid
      title: Cluster Tablet Object
      type: object
    ClusterTabletData:
      additionalProperties:
        $ref: '#/components/schemas/ClusterTablet'
      description: List of cluster tablets
      title: Cluster Tablet Data
      type: object
    VersionInfo:
      description: YugabyteDB version info
      example:
        version: version
      properties:
        version:
          type: string
      title: YugabyteDB Version Info
      type: object
    Cluster_Response:
      example:
        data:
          spec:
            cluster_region_info:
            - placement_info:
                cloud_info:
                  region: us-west2
                num_nodes: 22
            - placement_info:
                cloud_info:
                  region: us-west2
                num_nodes: 22
            name: name
            cloud_info:
              region: us-west2
            encryption_info:
              encryption_in_transit: false
              encryption_at_rest: false
            cluster_info:
              node_info:
                disk_size_used_gb: 5.962133916683182
                num_cores: 2
                memory_mb: 6.027456183070403
                cpu_usage: 5.637376656633329
                disk_size_gb: 1.4658129805029452
              is_production: false
              version: 7
              num_nodes: 2
          info:
            metadata:
              updated_on: updated_on
              created_on: created_on
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            state: state
            software_version: software_version
      properties:
        data:
          $ref: '#/components/schemas/ClusterData'
      title: Cluster Response
      type: object
    Cluster_Nodes_Response:
      example:
        data:
        - is_master_up: true
          is_master: true
          is_tserver: true
          is_node_up: true
          name: name
          host: host
          is_bootstrapping: true
          cloud_info:
            cloud: cloud
            zone: zone
            region: region
          metrics:
            system_tablets_total: 0
            system_tablets_leaders: 0
            write_ops_per_sec: 5.637376656633329
            ram_provisioned_bytes: 0
            time_since_hb_sec: 2.3021358869347655
            active_connections:
              ysql: 0
              ycql: 0
            total_sst_file_size_bytes: 6
            uncompressed_sst_file_size_bytes: 1
            read_ops_per_sec: 5.962133916683182
            user_tablets_leaders: 0
            ram_used_bytes: 0
            memory_used_bytes: 0
            uptime_seconds: 0
            user_tablets_total: 0
            disk_provisioned_bytes: 0
            master_uptime_us: 0
          software_version: software_version
        - is_master_up: true
          is_master: true
          is_tserver: true
          is_node_up: true
          name: name
          host: host
          is_bootstrapping: true
          cloud_info:
            cloud: cloud
            zone: zone
            region: region
          metrics:
            system_tablets_total: 0
            system_tablets_leaders: 0
            write_ops_per_sec: 5.637376656633329
            ram_provisioned_bytes: 0
            time_since_hb_sec: 2.3021358869347655
            active_connections:
              ysql: 0
              ycql: 0
            total_sst_file_size_bytes: 6
            uncompressed_sst_file_size_bytes: 1
            read_ops_per_sec: 5.962133916683182
            user_tablets_leaders: 0
            ram_used_bytes: 0
            memory_used_bytes: 0
            uptime_seconds: 0
            user_tablets_total: 0
            disk_provisioned_bytes: 0
            master_uptime_us: 0
          software_version: software_version
      properties:
        data:
          items:
            $ref: '#/components/schemas/NodeData'
          type: array
          uniqueItems: true
      required:
      - data
      title: Cluster Nodes Response
      type: object
    Metric_Response:
      example:
        data:
        - values:
          - - 0.8008281904610115
            - 0.8008281904610115
          - - 0.8008281904610115
            - 0.8008281904610115
          name: name
        - values:
          - - 0.8008281904610115
            - 0.8008281904610115
          - - 0.8008281904610115
            - 0.8008281904610115
          name: name
        end_timestamp: 1
        start_timestamp: 6
      properties:
        data:
          items:
            $ref: '#/components/schemas/MetricData'
          type: array
        start_timestamp:
          description: Start of range of results
          format: int64
          type: integer
        end_timestamp:
          description: End of range of results
          format: int64
          type: integer
      required:
      - data
      - end_timestamp
      - start_timestamp
      title: Metric Response
      type: object
    Cluster_table_list_response:
      example:
        data:
        - keyspace: keyspace
          size_bytes: 0
          name: name
        - keyspace: keyspace
          size_bytes: 0
          name: name
      properties:
        data:
          description: List of cluster tables
          items:
            $ref: '#/components/schemas/ClusterTable'
          nullable: false
          title: Cluster Table Data
          type: array
          uniqueItems: true
      required:
      - data
      title: Cluster table list response
      type: object
    Health_Check_Response:
      example:
        data:
          most_recent_uptime: 0
          dead_nodes:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          leaderless_tablets:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          under_replicated_tablets:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        data:
          $ref: '#/components/schemas/HealthCheckInfo'
      title: Health Check Response
      type: object
    Cluster_tablet_list_response:
      example:
        data:
          key:
            tablet_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            namespace: namespace
            table_uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            table_name: table_name
            has_leader: true
      properties:
        data:
          additionalProperties:
            $ref: '#/components/schemas/ClusterTablet'
          description: List of cluster tablets
          title: Cluster Tablet Data
          type: object
      required:
      - data
      title: Cluster tablet list response
      type: object
    Is_load_balancer_idle:
      description: Is load balancer idle
      example:
        is_idle: true
      properties:
        is_idle:
          type: boolean
      required:
      - is_idle
      title: Is load balancer idle
      type: object
    ApiError_error:
      properties:
        detail:
          description: Error message
          type: string
        status:
          description: Error code
          type: integer
      type: object
    NodeData_metrics_active_connections:
      example:
        ysql: 0
        ycql: 0
      properties:
        ysql:
          default: 0
          format: int64
          minimum: 0
          type: integer
        ycql:
          default: 0
          format: int64
          minimum: 0
          type: integer
      required:
      - ycql
      - ysql
      type: object
    NodeData_metrics:
      example:
        system_tablets_total: 0
        system_tablets_leaders: 0
        write_ops_per_sec: 5.637376656633329
        ram_provisioned_bytes: 0
        time_since_hb_sec: 2.3021358869347655
        active_connections:
          ysql: 0
          ycql: 0
        total_sst_file_size_bytes: 6
        uncompressed_sst_file_size_bytes: 1
        read_ops_per_sec: 5.962133916683182
        user_tablets_leaders: 0
        ram_used_bytes: 0
        memory_used_bytes: 0
        uptime_seconds: 0
        user_tablets_total: 0
        disk_provisioned_bytes: 0
        master_uptime_us: 0
      properties:
        memory_used_bytes:
          default: 0
          format: int64
          type: integer
        total_sst_file_size_bytes:
          default: 0
          format: int64
          nullable: true
          type: integer
        uncompressed_sst_file_size_bytes:
          default: 0
          format: int64
          nullable: true
          type: integer
        read_ops_per_sec:
          default: 0
          format: double
          type: number
        write_ops_per_sec:
          default: 0
          format: double
          type: number
        time_since_hb_sec:
          default: 0
          format: double
          type: number
        uptime_seconds:
          default: 0
          format: int64
          minimum: 0
          type: integer
        user_tablets_total:
          default: 0
          format: int64
          minimum: 0
          type: integer
        user_tablets_leaders:
          default: 0
          format: int64
          minimum: 0
          type: integer
        system_tablets_total:
          default: 0
          format: int64
          minimum: 0
          type: integer
        system_tablets_leaders:
          default: 0
          format: int64
          minimum: 0
          type: integer
        active_connections:
          $ref: '#/components/schemas/NodeData_metrics_active_connections'
        master_uptime_us:
          default: 0
          format: int64
          minimum: 0
          type: integer
        ram_used_bytes:
          default: 0
          format: int64
          minimum: 0
          type: integer
        ram_provisioned_bytes:
          default: 0
          format: int64
          minimum: 0
          type: integer
        disk_provisioned_bytes:
          default: 0
          format: int64
          minimum: 0
          type: integer
      required:
      - active_connections
      - disk_provisioned_bytes
      - master_uptime_us
      - memory_used_bytes
      - ram_provisioned_bytes
      - ram_used_bytes
      - read_ops_per_sec
      - system_tablets_leaders
      - system_tablets_total
      - time_since_hb_sec
      - total_sst_file_size_bytes
      - uncompressed_sst_file_size_bytes
      - uptime_seconds
      - user_tablets_leaders
      - user_tablets_total
      - write_ops_per_sec
      type: object
    NodeData_cloud_info:
      example:
        cloud: cloud
        zone: zone
        region: region
      properties:
        cloud:
          type: string
        region:
          type: string
        zone:
          type: string
      required:
      - region
      - zone
      type: object
  securitySchemes:
    BearerAuthToken:
      bearerFormat: JWT
      scheme: bearer
      type: http
